# Generated by Django 6.1.2 on 2026-10-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_reservation_email_reservation_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='special_requests',
            new_name='special_request',
        ),
    ]
